### ISSUE TITLE
rtiamb.publishObjectClassAttributes error in 2.1.0

### ISSUE THREAD

**Issue by bergtwvd** [openlvc/portico#175]
Portico 2.1.0, RPR-FOM 2.0, Java.

The following code stacktraces against 2.1.0, but works against 2.0.1.
Basically this is a showstopper for using 2.1.0 with RPR-FOM 2.0 (RPR-FOM 2D19 has the same problem, did not check further).

                /**
                * This method will inform the RTI about the types of data that we are
                * interested in.
                */
                private void publishAndSubscribe() throws RTIexception {
                               // get all the handle information for the attributes
                               this.entityHandle = rtiamb.getObjectClassHandle("HLAobjectRoot.BaseEntity.PhysicalEntity.Platform.Aircraft");
                               this.entityTypeHandle = rtiamb.getAttributeHandle(entityHandle, "EntityType");
                               this.spatialHandle = rtiamb.getAttributeHandle(entityHandle, "Spatial");
                               this.forceHandle = rtiamb.getAttributeHandle(entityHandle, "ForceIdentifier");
                               this.markingHandle = rtiamb.getAttributeHandle(entityHandle, "Marking");

                               // package the information into a handle set
                               attributes = rtiamb.getAttributeHandleSetFactory().create();
                               attributes.add(entityTypeHandle);
                               attributes.add(spatialHandle);
                               attributes.add(forceHandle);
                               attributes.add(markingHandle);

                               rtiamb.subscribeObjectClassAttributes(entityHandle, attributes);
                               rtiamb.publishObjectClassAttributes(entityHandle, attributes);

                               Main.logger.log(Level.INFO, "Published and Subscribed");
                }

STACKTRACE (2.1.0):
``
hla.rti1516e.exceptions.AttributeNotDefined: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.BaseEntity.PhysicalEntity.Platform.Aircraft]
                at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1161)
                at testfederate.Federate.publishAndSubscribe(Federate.java:154)
                at testfederate.Federate.runFederate(Federate.java:78)
                at testfederate.Main.main(Main.java:167)
Caused by: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.BaseEntity.PhysicalEntity.Platform.Aircraft]
                at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:160)
                at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:108)
                at org.portico.lrc.services.object.data.InterestManager.publishObjectClass(InterestManager.java:619)
                at org.portico.lrc.services.pubsub.handlers.outgoing.PublishObjectClassHandler.process(PublishObjectClassHandler.java:110)
                at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
                at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130)
                at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5559)
                at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1135)
                ... 3 more
``

**Comment by sharpplayer** [comment]
I have raised a pull request, which I believe fixes this.
Regards
sharp_player (Raymond Francis)

**Comment by anthonycramp** [comment]
Tom, Raymond,

The error does seem to be the result of privilegeToDelete returning INVALID_HANDLE. But, I think the fix needs to be in org.portico.lrc.model.ModelMerger.validate(), which I've copied below from 2.1.0:

	/**
	 * This method make sure that once all the modules are combined that the standard MIM
	 * types are present. If they're not, they will be merged in.
	 */
	private ObjectModel validate( ObjectModel model ) throws JInconsistentFDD
	{
		// ensure that HLAobjectRoot is present
		// ensure that HLAinteractionRoot is present
		// TBC
		return model;
	}

Previously, adding the MIM was done in org.portico.lrc.services.federation.handlers.outgoing.CreateFederationHandler.validateStandardMimPresent, but the call to that function has been commented out.

A quick fix (until Tim adds this functionality back into the Portico code) should be to just add the HLAprivilegeToDeleteObject attribute to the HLAobjectRoot class in one of your FOM modules or to include the standard MIM object model as part of the FOM module list when creating the federation.

**Comment by anthonycramp** [comment]
P.S. The standard MIM object model can be found in the Portico repository at codebase/resources/jar/portico.jar/etc/ieee1516e/HLAstandardMIM.xml. It's also in the portico.jar at etc/ieee1516e/HLAstandardMIM.xml.

**Comment by sharpplayer** [comment]
You also need to specify order and transportation.  I also did sharing for good measure (I guessed it was required after failing on the other two).  Looks like my PR can be forgotten after all as this workaround looks good.

**Comment by anthonycramp** [comment]
Glad it's working. Actually, I think your pull request is valid in a
slightly modified form. If privilegeToDelete is actually null in the
publish/delete contexts, then a better error would have been much more
useful. Perhaps replace your work around code with a logging call
mentioning the absence of the HLAprivilegeToDeleteObject attribute in the
FOM?

**Comment by timpokorny** [comment]
Gents! Firstly, thank-you for the work tracking this down! These comments and Ray's PR made things much simpler.

This came about due to a change to support the MOM for 1516e. The net result is that the MIM is now built and not just loaded. Due to this, `HLAprivilegeToDelete` was no longer being automatically loaded courtesy of the MIM. Booo.

@anthonycramp was right about checking that on validation, which now happens. I have pushed new commits to `master` which should fix this if someone can please confirm.

**Comment by bergtwvd** [comment]
As reporter of the issue happy to verify fix (next week), if someone provides me a jar... :-)
Thanks for the quick turnover!

**Comment by timpokorny** [comment]
@bergtwvd - The nightly build failed, but I have logged in to try and re-run it. It should be up at the following location some time in the next 30-60m: https://sourceforge.net/projects/portico/files/nightly/

**Comment by bergtwvd** [comment]
Downloaded and installed the nightly build.
When I run the code I still get the error.

Anything else I should do?

mei 16, 2016 3:44:25 PM testfederate.Federate connectAndJoin
INFO: Connected to RTI
mei 16, 2016 3:44:25 PM testfederate.Federate connectAndJoin
INFO: Creating Federation...

-------------------------------------------------------------------
GMS: address=PC-12505-30319, cluster=TheWorld, physical address=192.168.2.2:64419
-------------------------------------------------------------------
ERROR [main] portico.lrc.jgroups: FAILURE createFederation: already exists, name=TheWorld
mei 16, 2016 3:44:28 PM testfederate.Federate connectAndJoin
INFO: Didn't create federation, it already existed
mei 16, 2016 3:44:28 PM testfederate.Federate connectAndJoin
INFO: Joined Federation as TestFederate
hla.rti1516e.exceptions.AttributeNotDefined: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.BaseEntity.PhysicalEntity.Platform.Aircraft]
	at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1161)
	at testfederate.Federate.publishAndSubscribe(Federate.java:154)
	at testfederate.Federate.runFederate(Federate.java:76)
	at testfederate.Main.main(Main.java:167)
Caused by: org.portico.lrc.compat.JAttributeNotDefined: PUBLISH-OBJECT: attribute [-1] not defined in object class [HLAobjectRoot.BaseEntity.PhysicalEntity.Platform.Aircraft]
	at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:160)
	at org.portico.lrc.services.object.data.InterestManager.register(InterestManager.java:108)
	at org.portico.lrc.services.object.data.InterestManager.publishObjectClass(InterestManager.java:619)
	at org.portico.lrc.services.pubsub.handlers.outgoing.PublishObjectClassHandler.process(PublishObjectClassHandler.java:110)
	at org.portico.utils.messaging.MessageSink.process(MessageSink.java:187)
	at org.portico.impl.hla1516e.Impl1516eHelper.processMessage(Impl1516eHelper.java:130)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5559)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.publishObjectClassAttributes(Rti1516eAmbassador.java:1135)
	... 3 more
BUILD SUCCESSFUL (total time: 4 seconds)

**Comment by sharpplayer** [comment]
I had the same problem.  It looks like the jar file is still not built properly.  I took the source code, and built the jar file and it worked for me.  I thought I was the only one with the problem, but it appears not.

**Comment by anthonycramp** [comment]
Could be a bug in org.portico.lrc.model.ObjectModel.addPrivilegeToDeleteIfNotPresent called from org.portico.lrc.model.ModelMerger.validate.

It is only adding the HLA 1.3 privilegeToDelete attribute and not the 1516 HLAprivilegeToDeleteObject attribute.

**Comment by bergtwvd** [comment]
Tried the most recent nightly (portico-nightly-2016.05.17), and that works.
I'll close the issue.
